// web/components/shell/CommandPalette.tsx
"use client";

import { useState, useEffect, useCallback, useRef, useTransition } from "react";
import { useRouter } from "next/navigation";
import { motion, AnimatePresence, LayoutGroup } from "motion/react";
import { SITE, NAV_LINKS } from "@/lib/site";
import { springSoft } from "@/lib/motion";

interface Item { label: string; href: string; category: string; }

const ITEMS: Item[] = [
  { label: "Home", href: "/", category: "Page" },
  ...NAV_LINKS.map((l) => ({ ...l, category: "Page" })),
  { label: "GitHub", href: SITE.github, category: "External" },
  { label: "Discord", href: SITE.discord, category: "External" },
];

export default function CommandPalette() {
  const router = useRouter();
  const [, startTransition] = useTransition();
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);

  const filtered = query.trim()
    ? ITEMS.filter((item) =>
        item.label.toLowerCase().includes(query.toLowerCase()) ||
        item.category.toLowerCase().includes(query.toLowerCase())
      )
    : ITEMS;

  useEffect(() => {
    const onKeyDown = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "k") {
        e.preventDefault();
        setOpen((prev) => !prev);
      }
      if (e.key === "Escape" && open) setOpen(false);
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [open]);

  useEffect(() => {
    if (!open) {
      document.body.style.overflow = "";
      return;
    }
    document.body.style.overflow = "hidden";
    requestAnimationFrame(() => {
      inputRef.current?.focus();
      setQuery("");
      setSelected(0);
    });
    return () => { document.body.style.overflow = ""; };
  }, [open]);

  const navigate = useCallback(
    (href: string) => {
      setOpen(false);
      if (href.startsWith("http")) {
        window.open(href, "_blank", "noopener,noreferrer");
        return;
      }
      startTransition(() => router.push(href));
    },
    [router]
  );

  const onInputKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (e.key === "ArrowDown") { e.preventDefault(); setSelected((i) => Math.min(i + 1, filtered.length - 1)); }
      else if (e.key === "ArrowUp") { e.preventDefault(); setSelected((i) => Math.max(i - 1, 0)); }
      else if (e.key === "Enter") { e.preventDefault(); const item = filtered[selected]; if (item) navigate(item.href); }
    },
    [filtered, selected, navigate]
  );

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[220] flex items-start justify-center bg-[rgba(20,17,11,0.35)] px-4 pt-[18vh] backdrop-blur-[2px]"
          onClick={() => setOpen(false)}
        >
          <motion.div
            layoutId="condura-command"
            initial={{ opacity: 0, y: -8, scale: 0.98 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: -6, scale: 0.99 }}
            transition={springSoft}
            className="w-full max-w-xl overflow-hidden rounded-2xl border border-[rgba(20,17,11,0.14)] bg-[var(--color-paper)] shadow-[var(--shadow-float)] backdrop-blur-xl"
            onClick={(e) => e.stopPropagation()}
            role="dialog"
            aria-label="Command palette"
          >
            <div className="flex items-center gap-3 border-b border-[rgba(20,17,11,0.12)] px-4 py-3">
              <span className="text-[var(--color-ink-faint)]" aria-hidden>⌘K</span>
              <input
                ref={inputRef}
                type="text"
                inputMode="search"
                enterKeyHint="search"
                autoComplete="off"
                spellCheck={false}
                placeholder={`Search ${SITE.name}…`}
                value={query}
                onChange={(e) => { setQuery(e.target.value); setSelected(0); }}
                onKeyDown={onInputKeyDown}
                className="command-palette-input min-w-0 flex-1 border-0 bg-transparent py-2 text-sm text-[var(--color-ink)] shadow-none outline-none ring-0 placeholder:text-[var(--color-ink-faint)] focus:border-0 focus:shadow-none focus:outline-none focus:ring-0 focus-visible:border-0 focus-visible:shadow-none focus-visible:outline-none focus-visible:ring-0"
              />
            </div>
            <LayoutGroup>
              <ul className="max-h-[50vh] overflow-y-auto py-2" role="listbox">
                {filtered.length === 0 ? (
                  <li className="px-4 py-6 text-center text-sm text-[var(--color-ink-mute)]">No matches</li>
                ) : (
                  filtered.map((item, index) => (
                    <li key={item.label + item.href}>
                      <button
                        type="button"
                        role="option"
                        aria-selected={index === selected}
                        onMouseEnter={() => setSelected(index)}
                        onClick={() => navigate(item.href)}
                        className={`relative flex w-full items-center justify-between px-4 py-2.5 text-left text-sm ${
                          index === selected ? "text-[var(--color-ink)]" : "text-[var(--color-ink-mute)]"
                        }`}
                      >
                        {index === selected && (
                          <motion.span
                            layoutId="palette-highlight"
                            className="absolute inset-x-2 inset-y-0 rounded-lg bg-[rgba(20,17,11,0.06)]"
                            transition={springSoft}
                          />
                        )}
                        <span className="relative z-10">{item.label}</span>
                        <span className="relative z-10 text-[11px] text-[var(--color-ink-faint)]">{item.category}</span>
                      </button>
                    </li>
                  ))
                )}
              </ul>
            </LayoutGroup>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

// condura-gui/frontend/src/lib/components/ui/CommandPalette.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'

  interface Item {
    id: string
    label: string
    hint?: string
    group?: string
    shortcut?: string
    icon?: Snippet
    onselect?: () => void
    disabled?: boolean
  }

  interface Props {
    open: boolean
    items: Item[]
    placeholder?: string
    emptyMessage?: string
    onclose?: () => void
  }

  let { open = $bindable(false), items, placeholder = 'Search…',
        emptyMessage = 'No results', onclose }: Props = $props()

  let query = $state('')
  let inputEl = $state<HTMLInputElement | null>(null)
  let activeIdx = $state(0)

  const filtered = $derived.by(() => {
    if (!query.trim()) return items
    const q = query.toLowerCase()
    return items.filter(it =>
      it.label.toLowerCase().includes(q) ||
      (it.hint?.toLowerCase().includes(q)) ||
      (it.group?.toLowerCase().includes(q))
    )
  })

  function close(): void {
    open = false
    query = ''
    activeIdx = 0
    onclose?.()
  }

  function run(item: Item): void {
    if (item.disabled) return
    item.onselect?.()
    close()
  }

  function onKey(e: KeyboardEvent): void {
    if (!open) return
    if (e.key === 'Escape') { close(); return }
    if (e.key === 'ArrowDown') {
      e.preventDefault()
      activeIdx = Math.min(activeIdx + 1, filtered.length - 1)
    } else if (e.key === 'ArrowUp') {
      e.preventDefault()
      activeIdx = Math.max(activeIdx - 1, 0)
    } else if (e.key === 'Enter') {
      e.preventDefault()
      const item = filtered[activeIdx]
      if (item) run(item)
    }
  }

  $effect(() => {
    if (open) {
      queueMicrotask(() => inputEl?.focus())
      activeIdx = 0
    }
  })

  $effect(() => { query; activeIdx = 0 })
</script>

<svelte:window onkeydown={onKey} />

{#if open}
  <div class="cmd-backdrop anim-fade" onclick={close} role="presentation"></div>
  <div class="cmd-shell anim-pop" role="combobox" aria-expanded="true" aria-controls="cmd-results" aria-haspopup="listbox">
    <header class="cmd-input-row">
      <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" class="cmd-search-icon" aria-hidden="true">
        <circle cx="11" cy="11" r="7" />
        <path d="M21 21l-4.3-4.3" />
      </svg>
      <input
        bind:this={inputEl}
        bind:value={query}
        class="cmd-input"
        type="text"
        {placeholder}
        spellcheck="false"
        autocomplete="off"
      />
    </header>
    <div class="cmd-results">
      {#if filtered.length === 0}
        <div class="cmd-empty">{emptyMessage}</div>
      {:else}
        {#each filtered as item, i (item.id)}
          <button
            type="button"
            class="cmd-item"
            class:active={i === activeIdx}
            class:disabled={item.disabled}
            onmouseenter={() => activeIdx = i}
            onclick={() => run(item)}
          >
            {#if item.icon}<span class="cmd-icon">{@render item.icon()}</span>{/if}
            <span class="cmd-text">
              <span class="cmd-label">{item.label}</span>
              {#if item.hint}<span class="cmd-hint">{item.hint}</span>{/if}
            </span>
            {#if item.shortcut}<span class="cmd-shortcut">{item.shortcut}</span>{/if}
          </button>
        {/each}
      {/if}
    </div>
  </div>
{/if}

<style>
  .cmd-backdrop {
    position: fixed;
    inset: 0;
    background: var(--surface-overlay);
    backdrop-filter: var(--glass-blur);
    -webkit-backdrop-filter: var(--glass-blur);
    z-index: var(--z-modal);
  }

  .cmd-shell {
    position: fixed;
    top: 18%;
    left: 50%;
    transform: translateX(-50%);
    width: 100%;
    max-width: 580px;
    max-height: 60vh;
    background: var(--surface-2);
    border: 1px solid var(--border-strong);
    border-radius: var(--radius-xl);
    box-shadow: var(--shadow-2xl);
    z-index: var(--z-modal);
    display: flex;
    flex-direction: column;
    overflow: hidden;
  }

  .cmd-input-row {
    display: flex;
    align-items: center;
    gap: var(--space-3);
    padding: var(--space-4) var(--space-5);
    border-bottom: 1px solid var(--border);
  }
  .cmd-search-icon { color: var(--text-faint); flex-shrink: 0; }
  .cmd-input {
    flex: 1;
    background: transparent;
    border: none;
    outline: none;
    color: var(--text);
    font-family: var(--font-sans);
    font-size: var(--size-md);
  }
  .cmd-input::placeholder { color: var(--text-faint); }

  .cmd-results {
    flex: 1;
    overflow-y: auto;
    padding: var(--space-2);
  }

  .cmd-empty {
    padding: var(--space-7) var(--space-5);
    text-align: center;
    color: var(--text-faint);
    font-size: var(--size-sm);
  }

  .cmd-item {
    appearance: none;
    background: transparent;
    border: none;
    color: var(--text);
    width: 100%;
    text-align: left;
    padding: var(--space-3) var(--space-4);
    border-radius: var(--radius-md);
    cursor: pointer;
    display: flex;
    align-items: center;
    gap: var(--space-3);
    font-family: var(--font-sans);
    transition: background-color var(--transition-fast) ease;
  }
  .cmd-item.active { background: var(--surface-3); }
  .cmd-item.disabled { opacity: 0.5; cursor: not-allowed; }

  .cmd-icon { color: var(--text-faint); flex-shrink: 0; display: inline-flex; }
  .cmd-text { flex: 1; min-width: 0; display: flex; flex-direction: column; gap: 2px; }
  .cmd-label { font-size: var(--size-sm); color: var(--text); font-weight: var(--weight-medium); }
  .cmd-hint  { font-size: var(--size-xs); color: var(--text-muted); }
  .cmd-shortcut {
    font-family: var(--font-mono);
    font-size: 10px;
    color: var(--text-faint);
    padding: 2px 6px;
    background: var(--surface-3);
    border-radius: var(--radius-sm);
    flex-shrink: 0;
  }
</style>
