// web/components/motion/Tooltip.tsx
"use client";

import { useId, useState, type ReactNode } from "react";
import { AnimatePresence, motion } from "motion/react";

interface TooltipProps {
  label: string;
  children: ReactNode;
  side?: "top" | "bottom";
}

export default function Tooltip({ label, children, side = "top" }: TooltipProps) {
  const [open, setOpen] = useState(false);
  const id = useId();

  return (
    <span
      className="relative inline-flex"
      onMouseEnter={() => setOpen(true)}
      onMouseLeave={() => setOpen(false)}
      onFocus={() => setOpen(true)}
      onBlur={() => setOpen(false)}
    >
      <span aria-describedby={open ? id : undefined}>{children}</span>
      <AnimatePresence>
        {open && (
          <motion.span
            id={id}
            role="tooltip"
            initial={{ opacity: 0, y: side === "top" ? 6 : -6, scale: 0.96 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: side === "top" ? 4 : -4, scale: 0.98 }}
            transition={{ duration: 0.14 }}
            className={`pointer-events-none absolute left-1/2 z-50 -translate-x-1/2 whitespace-nowrap rounded-md border border-white/[0.08] bg-[#111113]/95 px-2 py-1 text-[11px] text-white/80 shadow-lg backdrop-blur-xl ${
              side === "top" ? "bottom-full mb-2" : "top-full mt-2"
            }`}
          >
            {label}
          </motion.span>
        )}
      </AnimatePresence>
    </span>
  );
}

// condura-gui/frontend/src/lib/components/ui/Tooltip.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'

  interface Props {
    text: string
    side?: 'top' | 'bottom' | 'left' | 'right'
    delay?: number
    children: Snippet
  }

  let { text, side = 'top', delay = 200, children }: Props = $props()

  let open = $state(false)
  let timer: ReturnType<typeof setTimeout> | null = null

  function show(): void {
    if (timer) clearTimeout(timer)
    timer = setTimeout(() => { open = true }, delay)
  }
  function hide(): void {
    if (timer) { clearTimeout(timer); timer = null }
    open = false
  }
</script>

<span
  class="tooltip-host"
  onmouseenter={show}
  onmouseleave={hide}
  onfocusin={show}
  onfocusout={hide}
  role="presentation"
>
  {@render children()}
  {#if open}
    <span class="tooltip tooltip-{side}" role="tooltip">{text}</span>
  {/if}
</span>

<style>
  .tooltip-host { position: relative; display: inline-flex; }

  .tooltip {
    position: absolute;
    z-index: var(--z-overlay);
    background: var(--surface-3);
    color: var(--text);
    border: 1px solid var(--border-strong);
    border-radius: var(--radius-sm);
    padding: 4px 8px;
    font-size: var(--size-xs);
    white-space: nowrap;
    box-shadow: var(--shadow-md);
    pointer-events: none;
    animation: fade-in var(--transition-fast) ease both;
  }

  .tooltip-top    { bottom: calc(100% + 6px); left: 50%; transform: translateX(-50%); }
  .tooltip-bottom { top:    calc(100% + 6px); left: 50%; transform: translateX(-50%); }
  .tooltip-left   { right:  calc(100% + 6px); top: 50%;  transform: translateY(-50%); }
  .tooltip-right  { left:   calc(100% + 6px); top: 50%;  transform: translateY(-50%); }
</style>
